--
-- This SQL migration has been adapted to the project.
-- 
-- Source: Supabase Todo Quickstart with Row Level Security
--

create table todos (
  id bigint generated by default as identity primary key,
  inserted_at timestamp with time zone default timezone('utc'::text, now()) not null
  is_complete boolean default false,
  task text check (char_length(task) > 3),
  user_id uuid references auth.users not null,
);

alter table todos enable row level security;

create policy "TODO_INSERT_POLICY" on todos for
    insert with check (auth.uid() = user_id);
create policy "TODO_SELECT_POLICY" on todos for
    select using (true);
create policy "TODO_UPDATE_POLICY" on todos for
    update using ((select auth.uid()) = user_id);
create policy "TODO_DELETE_POLICY" on todos for
    delete using ((select auth.uid()) = user_id);
